# Generated by Django 5.2 on 2025-05-07 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('files', models.FileField(upload_to='uploads/')),
                ('submit_time', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '文件记录',
                'verbose_name_plural': '文件记录',
            },
        ),
    ]
